# 수치형 변수 변환하기


### 주어진 데이터에서 'f5'컬럼을 표준화(Standardization (Z-score Normalization))하고 그 중앙값을 구하시오
- 데이터셋 : basic1.csv
- 오른쪽 상단 copy&edit 클릭 -> 예상문제 풀이 시작

## Standardization (Z-score Normalization)

![standard](https://wikimedia.org/api/rest_v1/media/math/render/svg/b0aa2e7d203db1526c577192f2d9102b718eafd5)

In [32]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
from sklearn.preprocessing import StandardScaler
df = pd.read_csv('/kaggle/input/bigdatacertificationkr/basic1.csv')

In [18]:
print(df[['f5']].shape)
print(df['f5'].shape)

(100, 1)
(100,)

In [43]:
# 표준화
scaler = StandardScaler()
df['f5']=scaler.fit_transform(df[['f5']])
df['f5']

0     1.220815
1     0.127343
2    -1.394535
3    -0.143667
4    -0.970085
        ...
95   -0.143667
96    0.393896
97    1.472730
98    1.435683
99   -0.827418
Name: f5, Length: 100, dtype: float64

In [44]:
# 중앙값 출력
print(df['f5'].median())

0.26061962955901474

## Hint
- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
- https://en.wikipedia.org/wiki/Feature_scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
data = [[0, 2], [0.4, 0.2], [1.1, 10], [11, 19], [34, 21], [6, 40]]
scaler = StandardScaler()
print(scaler.fit(data))
print(scaler.transform(data))

## 풀이

In [40]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
import numpy as np

df = pd.read_csv('../input/bigdatacertificationkr/basic1.csv')
df.head(2)

     id  age city    f1  f2   f3    f4         f5
0  id01  2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02  9.0   서울  70.0   1  NaN  ENFJ  60.339826

In [41]:
# 표준화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['f5']=scaler.fit_transform(df[['f5']])
df.head()

     id   age city    f1  f2   f3    f4        f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  1.220815
1  id02   9.0   서울  70.0   1  NaN  ENFJ  0.127343
2  id03  27.0   서울  61.0   1  NaN  ISTJ -1.394535
3  id04  75.0   서울   NaN   2  NaN  INFP -0.143667
4  id05  24.0   서울  85.0   2  NaN  ISFJ -0.970085

In [42]:
# 중앙값 출력
print(df['f5'].median())

0.260619629559015